feat: Add Syrup OFT addresses (SC-18421)
maple-labs/address-registry pull request #37
Opened 2024-11-11 14:27 UTC by JGcarv

2024-11-12 06:46 UTC, 0xfarhaan requested changes

2024-11-12 06:46 UTC, 0xfarhaan commented on MapleAddressRegistryBASEL2.md
> +| syrup | [0x7E0e1fE79594f738A4deA8Bb1085C9626f0935bC](https://basescan.io/address/0x7E0e1fE79594f738A4deA8Bb1085C9626f0935bC) |
Syrup OFT

2024-11-12 06:46 UTC, 0xfarhaan commented on MapleAddressRegistryETH.md
> +| OftAdapter | [0x7E0e1fE79594f738A4deA8Bb1085C9626f0935bC](https://etherscan.io/address/0x7E0e1fE79594f738A4deA8Bb1085C9626f0935bC) |
Syrup - OftAdaptor

2024-11-15 08:18 UTC, 0xfarhaan approved these changes

2024-11-15 08:19 UTC, merged

2024-11-24 17:01 UTC, dabossdana reviewed
Run